### ISSUE TITLE
Add in Linux kernel sources

### ISSUE THREAD

**Issue by jlazkano** [cilynx/rtl88x2bu#105]
Hello,

This works perfect in the last Debian stable distribution.

Is it possible to add this code in the Linux kernel source? Is missing something to not include it?

Thanks for your help.

**Comment by hectorugc** [comment]
How do i do that man?

**Comment by jlazkano** [comment]
Hello,

No idea, but there are some mail-list where we could ask for it:

http://driverdev.linuxdriverproject.org/mailman/listinfo/driverdev-devel

Best regards.
