### ISSUE TITLE
5.9 liquorix kernel

### ISSUE THREAD

**Issue by sunta3iouxos** [cilynx/rtl88x2bu#107]
works perfectly with the latest  liquorix kernel (https://liquorix.net/#install) on linuxmint 20.4

**Comment by MaxG87** [comment]
Thank you for your feedback. Which branch did you use?

**Comment by sunta3iouxos** [comment]
git branch --all
* 5.6.1_30362.20181109_COEX20180928-6a6a
  remotes/origin/5.6.1.6_35492.20191025_COEX20180928-6a6a
  remotes/origin/5.6.1_30362.20181109_COEX20180928-6a6a
  remotes/origin/HEAD -> origin/5.6.1_30362.20181109_COEX20180928-6
