### ISSUE TITLE
Disable 5ghz band

### ISSUE THREAD

**Issue by GuyCoast** [cilynx/rtl88x2bu#119]
I am using debian on beaglebone black and the driver works perfectly.
For better long distance stability, I would need to disable the 5ghz band. Is it possible by changing the configuration in makefile?

**Comment by AGenchev** [comment]
Why - you can just select your 2.4 GHz BSSID. I have TP-Link router and the 2 bands have different BSSID.

**Comment by GuyCoast** [comment]
> Why - you can just select your 2.4 GHz BSSID. I have TP-Link router and the 2 bands have different BSSID.

ok thanks for the reply, i will try to use the bssid
