### ISSUE TITLE
Switch to  5.8.7.1_35809.20191129_COEX20191120-7777 as default branch

### ISSUE THREAD

**Issue by MaxG87** [cilynx/rtl88x2bu#122]
With the most recent commits 5.6.1.6_35492.20191025_COEX20180928-6a6a should contain every addition and fix that was added to the 5.6.1_... branch. I think its time to make it the main branch.

**Comment by MaxG87** [comment]
I just pushed a new branch:  5.8.7.1_35809.20191129_COEX20191120-7777. I think I applied all necessary adaptions on it already.

Lets directly switch to  5.8.7.1_35809.20191129_COEX20191120-7777 please!

**Comment by MaxG87** [comment]
Confirmed to work on Debian Bullseye with Kernel 5.10.0-2. Works good enough to post this comment.

```bash
$ uname -a
Linux hostname 5.10.0-2-amd64 #1 SMP Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux
```

**Comment by MaxG87** [comment]
I overlooked some merge conflict lines. #124 blocks this issue atm.

**Comment by MaxG87** [comment]
#124 is resolved. Please lets reconsider to switch to 5.8.7.1 as default branch.

**Comment by AGenchev** [comment]
I guess he didn't switch because per issue #144 it didn't compile on RPI....

**Comment by MaxG87** [comment]
Thank you for bringing #144 to my attention. In the meantime I created #148 , which should solve that issue.

**Comment by AGenchev** [comment]
Thank you for working on it!

**Comment by cilynx** [comment]
Default branch has been updated to 5.8.7.1_35809.20191129_COEX20191120-7777

**Comment by MaxG87** [comment]
Thank you very much.
