### ISSUE TITLE
Merge issue 

### ISSUE THREAD

**Issue by ryleyb** [cilynx/rtl88x2bu#124]
Looks like some merge stuff got accidentally committed here...

https://github.com/cilynx/rtl88x2bu/blob/ba12c4f939948c1b16db7276da94feeef294da6c/os_dep/linux/rtw_proc.c#L5072

**Comment by MaxG87** [comment]
Thank you for noticing. The error was introduced in 822ca8a494024231b6798a0eaff208b7f02a4d43 where I cherry picked 4 individual commits. The commits are named in the commit message.

Resolving their merge conflicts is quite tough. I would welcome a helping hand here but I will retry cherry-picking the entire thing soon on my own too.

**Comment by MaxG87** [comment]
I fixed the merges with the most recent force-push. Please open a new issue in case of any problems.
