### ISSUE TITLE
Error building on latest kernel (5.11.2)

### ISSUE THREAD

**Issue by hood** [cilynx/rtl88x2bu#131]
Building fails on latest kernel with error
```
/rtl88x2bu/os_dep/linux/ioctl_cfg80211.c:442:3: error: too few arguments to function fg80211_ch_switch_started_notify
```

This is due to `cfg80211_ch_switch_started_notify` changing it signature and requiring one more last parameter to be passed (`quiet`, a boolean flag)

**Comment by MaxG87** [comment]
Thank you for opening this Issue. It should be fixed with the latest commits on 5.6.1.6 and 5.8.1 .
