### ISSUE TITLE
Allow setting network namespace

### ISSUE THREAD

**Issue by oofnikj** [cilynx/rtl88x2bu#15]
First of all thanks for taking the time to publish your work on this driver.

I'd like to use it in my [project](https://github.com/oofnikj/docker-openwrt/) which requires support for setting the network namespace for the phy interface, but I receive the following error when running the command to do so:
```
$ sudo iw phy phy5 set netns 7793
command failed: Operation not supported (-95)
```
I've attached a patch which sets the relevant `wiphy` flag, but beyond that I'm lost.

Here's a similar patch for `brcmfmac`: https://patchwork.kernel.org/patch/9624591/
Any help would be appreciated!

[0001-NETNS_OK-flag.patch.txt](https://github.com/cilynx/rtl88x2bu/files/4248492/0001-NETNS_OK-flag.patch.txt)

**Comment by MaxG87** [comment]
PR #66 should have added that.
