### ISSUE TITLE
Build fails on 64 bit raspberry pi

### ISSUE THREAD

**Issue by desultory-zz** [cilynx/rtl88x2bu#170]
I fixed it by changing these lines in the makefile:

`ifeq ($(CONFIG_PLATFORM_ARM_RPI), y)
                ARCH := arm64
        else
                ARCH := arm64
        endif`

**Comment by cilynx** [comment]
I think I have a fix for this -- testing a few platforms to make sure before pushing it.

**Comment by desultory-zz** [comment]
I was able to fix it just by overriding it, I think it's just an issue with the wrong ARCH being used.  I never got these drivers to work quite right, I ended up using these: https://github.com/morrownr/88x2bu

I'm using this device: https://www.amazon.com/gp/product/B088WLMQFB?ref=ppx_pt2_dt_b_prod_image&th=1

**Comment by cilynx** [comment]
You're correct that it's just the wrong arch being used, but I need to make sure it detects rpi aarch64 correctly as arm64 while still getting the other platforms right as well.  Tested on 64-bit Raspberry Pi 4, 32-bit Raspberry Pi 1B, and on x86 PC.

**Comment by desultory-zz** [comment]
Were you able to get full AC AP support with the drivers? I was only able to get N speeds at about 150mbps
