### ISSUE TITLE
Missing net/ipx.h

### ISSUE THREAD

**Issue by 0xf0xx0** [cilynx/rtl88x2bu#171]
Seems to be related to this https://lkml.org/lkml/2021/9/1/999

Kernel version: 5.15.0-rc3-1-mainline

Distro: Arch

**Comment by cilynx** [comment]
Thank you for the report.  Please try the new remove_ipx branch.  (aba46cd4dfe721df79fb24f7c9097f2b54006df3)

Confirmed working on Debian/sid running 5.14 and Ubuntu/21.10 running 5.15-rc3.

**Comment by 0xf0xx0** [comment]
Cool, that compiled and it's working :3

**Comment by cilynx** [comment]
Sweet -- looks like @MaxG87 pushed this same change to the main branch with e3339ad63c0a51e353f714743b8f0124ec2d89ba, so I cleaned up my remove_ipx branch and we should be all good here.
