### ISSUE TITLE
"Unknown symbol in modlue or unknown parameter" on Ubuntu 21.04

### ISSUE THREAD

**Issue by LordUbuntu** [cilynx/rtl88x2bu#178]
# The Problem

Previously the setup for rtl88x2bu on dkms worked superbly and never failed me. However, this time there are issues I am too stupid to know the answer to, and so I humbly submit all that I know so far, and I will provide more information on request.

# The Process

## Remove Module

To ensure that there would be no problems I started the process by making sure that old modules were removed from the system in totality, and so I followed the instructions on that to a T, that being:
```
sudo dkms remove rtl88x2bu/5.8.7.4 --all
find /lib/modules -name cfg80211.ko -ls
sudo rm -f /lib/modules/*/updates/net/wireless/cfg80211.ko
```
by the letter! No troubles occurred so I moved on to the next step.
`sudo modprobe cfg80211`
and it reported `modprobe: FATAL: Module cfg80211 not found in directory /lib/modules/5.13.0-7614-generic`

## Install Module

I ignored this error in the hopes that it isn't important (what is cfg80211 btw?) and continued to the next step of installing the new modules manually like I had the last time. This went without a hitch, all the command below worked without any problems
```
VER=$(sed -n 's/\PACKAGE_VERSION="\(.*\)"/\1/p' dkms.conf)
sudo rsync -rvhP ./ /usr/src/rtl88x2bu-${VER}
sudo dkms add -m rtl88x2bu -v ${VER}
sudo dkms build -m rtl88x2bu -v ${VER} # Takes ~3-minutes on a 3B+
sudo dkms install -m rtl88x2bu -v ${VER}
```

However, when I went to activate the 88x2bu module with `sudo modprobe 88x2bu` I received the response `modprobe: ERROR: could not insert '88x2bu': Unknown symbol in module, or unknown parameter (see dmesg)` and upon running dmesg I got (summarized because it's on a different computer and we'd be here all day if I typed this out by hand):
```
[5516.73...] 88x2bu: Unknown symbol cfg80211.* (err -2)
[5516.73...] 88x2bu: Unknown symbol wiphy.* (err -2)
```
which worryingly brings up cfg80211 a lot...

# Conclusion

What's wrong with it? How do I fix this?

**Comment by martadinata666** [comment]
Force reinstall kernel, its in `linux-image-bla2`, what you need is remove `88x2.ko` / `88x2bu.ko`. `cfg80211` is basic module for all wireless.

**Comment by LordUbuntu** [comment]
Ok, I'll try a full kernel reinstall and let you know how it goes later!

**Comment by LordUbuntu** [comment]
I got a chance to test it. Yes, a full kernel reinstall will work perfectly. If you run into a similar error, you know the cause: cfg80211 is missing (which is a crucial kernel driver for wifi as I found out), so you will have to reinstall to get it back, after which the process is just standard.

**Comment by LordUbuntu** [comment]
I got a chance to test it. Yes, a full kernel reinstall will work perfectly. If you run into a similar error, you know the cause: cfg80211 is missing (which is a crucial kernel driver for wifi as I found out), so you will have to reinstall to get it back, after which the process is just standard.
