### ISSUE TITLE
Does this driver automatically load a firmware blob?

### ISSUE THREAD

**Issue by Peter4487** [cilynx/rtl88x2bu#190]
First, thank you *so much* for your work here! I use this a lot and it's wonderful.

Most of the programming I do is web-related. I was trying to look through the source to figure out if it downloads and then loads a proprietary firmware blob onto the chip. It looks like maybe it does? I can't really tell.

As this is an issue I've opened, I'll suggest an improvement: many of the people coming here to use your software are motivated to use FLOSS, of course. Perhaps it would be good to mention if it uses a proprietary firmware blob and how it does that in the readme.

Thanks again!!!

**Comment by MaxG87** [comment]
Hello. Thank you very much for your comment.

I have to admit that I do not know an answer to your question. I am just fixing compile errors but I do not have any further knowledge. If you find out something, please let me know.
