### ISSUE TITLE
Build working on Ubuntu 18.04, Kernel 5.4 and 5.7, but DKMS build error = 10 on Kernel 5.10 and 5.15

### ISSUE THREAD

**Issue by TbilisiHeat** [cilynx/rtl88x2bu#192]

**Comment by TbilisiHeat** [comment]
I wanted to mention, I was tearing my hair out about this all day today, and I couldn't figure it out until downgrading kernel from 5.10 and 5.15 to LTS 5.4.  I am a relative newbie to Linux and kept getting the following errors on Kernels 5.1 and 5.15:

cleaning build area...(bad exit status: 2)
An error occurred. dkms build error = 10

The issue subsided when rolling back to 5.7 and 5.4.  I hope this helps anyone having a similar issue.

**Comment by VergeDX** [comment]
I built on NixOS with kernel `5.15.16-lqx2`, it works fine.
https://github.com/Vanilla-s-Lab/flakes/commit/fbd18f4029734e3806ec99e29be5e04fa18dab59
