### ISSUE TITLE
build with xubuntu 20.04.3 / kernel 5.13.0-27

### ISSUE THREAD

**Issue by HoppMarc** [cilynx/rtl88x2bu#193]
https://askubuntu.com/questions/1388628/xubuntu-usb-wifi-driver-lost-with-recent-update?noredirect=1#comment2398458_1388628

**Comment by borisrunakov** [comment]
Same here. After updating KDE Neon to `5.13.0-27-generic` the driver does not work. 
```
Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.13.0-27-generic KVER=5.13.0-27-generic src=/usr/src/rtl88x2bu-5.6.1.......(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.13.0-27-generic (x86_64)
```

**Comment by Muscule** [comment]
same ubuntu-budgie

**Comment by MaxG87** [comment]
I just answered on askubuntu.com.

In a nutshell, you are using an EOL version of the driver. Please make sure you are using 5.8.7.1 and not 5.6.1.
