### ISSUE TITLE
modprobe: ERROR: could not insert '88x2bu': Exec format error

### ISSUE THREAD

**Issue by Fr3nzy-029** [cilynx/rtl88x2bu#202]
I installed the driver in my Kubuntu 20.04 referring [this](https://community.tp-link.com/en/home/forum/topic/208022) for TP-Link AC1300. It was working good.
But after upgrading to Kubuntu 21.10, the adapter didn't work. I executed the commands in above link again, but the dkms operations skipped execution with message that they were already installed (on kernel 5.13.0-39-generic/x86_64).
When I executed modprobe I got this response
`modprobe: ERROR: could not insert '88x2bu': Exec format error`
How to fix this? Are there any commands to be executed when we upgrade the distro or change kernel? Please help with the fix.

**Comment by MaxG87** [comment]
Kubuntu 21.10 is already deprecated to my knowledge. The non LTS versions are supported for only 9 months.

Anyhow, I cannot recall to have seen an `Exec format error`. Could you try to
1. checkout the latest branch (5.8.7.1)
2. compile it manually and
3. try to insert it via `insmod`?
