### ISSUE TITLE
error 'gro_drop

### ISSUE THREAD

**Issue by alwzfolwd** [cilynx/rtl88x2bu#204]
im trying to build the driver and keep getting this error. I've searched all over and have yet to find an answer.

toxictech@Master:~/Downloads/rtl8814au$ sudo make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.13.0-39-generic/build M=/home/toxictech/Downloads/rtl8814au  modules
make[1]: Entering directory '/usr/src/linux-headers-5.13.0-39-generic'
  CC [M]  /home/toxictech/Downloads/rtl8814au/os_dep/linux/recv_linux.o
/home/toxictech/Downloads/rtl8814au/os_dep/linux/recv_linux.c: In function ‘napi_recv’:
/home/toxictech/Downloads/rtl8814au/os_dep/linux/recv_linux.c:358:55: error: ‘GRO_DROP’ undeclared (first use in this function)
  358 |    if (rtw_napi_gro_receive(&padapter->napi, pskb) != GRO_DROP)
      |                                                       ^~~~~~~~
/home/toxictech/Downloads/rtl8814au/os_dep/linux/recv_linux.c:358:55: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:281: /home/toxictech/Downloads/rtl8814au/os_dep/linux/recv_linux.o] Error 1
make[1]: *** [Makefile:1879: /home/toxictech/Downloads/rtl8814au] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.13.0-39-generic'
make: *** [Makefile:2353: modules] Error 2

**Comment by CGarces** [comment]
That was fixed on https://github.com/cilynx/rtl88x2bu/commit/8316868608bd0fc3de48dd7d5d7ebe4648f5a181

Please double check if you are using the last version of the default branch.
