### ISSUE TITLE
5Ghz limited to 1Mbps while 2.4 on sub-par speeds.

### ISSUE THREAD

**Issue by newedgex** [cilynx/rtl88x2bu#208]
I'm using the driver for my ID 2357:012d TP-Link Archer T3U [Realtek RTL8812BU]
I first tried to connect in 5Ghz mode and the connection worked but the download speed was capped at 1Mbps, then I tried to connect to the 2.4Ghz and while the download was 10x more, it was still at 20% of capacity.

To give you an example, I get 
- 45Mbps with TP-Link TL-WN722N v2/v3 [Realtek RTL8188EUS] (supports only 2.4Ghz)
- 10Mbps with TP-Link Archer T3U [Realtek RTL8812BU] in 2.4Ghz
- 1Mbps with TP-Link Archer T3U [Realtek RTL8812BU] in 5Ghz mode

I'm on Arch linux with latest available kernel : 5.18.5-arch1-1 (at this point).

```kms status
8188eu/5.2.2.4.r803.903b6fc, 5.18.5-arch1-1, x86_64: installed
rtl88x2bu/r112.9957138, 5.18.5-arch1-1, x86_64: installed
```

**Comment by EdsonLuiz** [comment]
Maybe your problem is related to this [Linux 5.18+ and RTW88 Driver](https://github.com/RinCat/RTL88x2BU-Linux-Driver#linux-518-and-rtw88-driver)
