### ISSUE TITLE
Kernel headers cannot be found (already installed) - Linux

### ISSUE THREAD

**Issue by federicorojas11** [cilynx/rtl88x2bu#211]
I have the following output when I run install-driver.sh file

```
Running install-driver.sh version 20220108
Operating System: Kali GNU/Linux Rolling
5.16.0-kali7-amd64
x86_64
Starting installation...
Copying source files to: /usr/src/rtl88x2bu-5.13.1
Copying 88x2bu.conf to: /etc/modprobe.d
Creating symlink /var/lib/dkms/rtl88x2bu/5.13.1/source -> /usr/src/rtl88x2bu-5.13.1
Error! Your kernel headers for kernel 5.16.0-kali7-amd64 cannot be found at /lib/modules/5.16.0-kali7-amd64/build or /lib/modules/5.16.0-kali7-amd64/source.
Please install the linux-headers-5.16.0-kali7-amd64 package or use the --kernelsourcedir option to tell DKMS where it's located.
An error occurred. dkms build error = 1
Please report this error.
You will need to run the following before reattempting installation.
$ sudo ./remove-driver.sh
```

Also I checked those folders and do not exist by the way.
When I go into /lib/modules//5.16.0-kali7-amd64
There is a kernel folder, and some other stuff (modules files).
When I enter kernel folder I found these folders
`arch  block  crypto  drivers  fs  lib  mm  net  sound  virt
`
Finally tried to execute 
`└─$ sudo ./install-driver.sh --kernelsourcedir /lib/modules/5.16.0-kali7-amd64
`but didn't work, and received this as output
```
Syntax ./install-driver.sh <NoPrompt>
       NoPrompt - noninteractive mode
       -h|--help - Show help
```
Which should be the kernel headers folder that I should declare and how can I do it?
Thanks

**Comment by MaxG87** [comment]
Is this related to #205 ?
