### ISSUE TITLE
Branch fix-6.0 also partially needed for 5.19.3

### ISSUE THREAD

**Issue by Fjodor42** [cilynx/rtl88x2bu#218]
Discovering #217, I wanted to downgrade to 5.19.3.

Then I discovered that in order for the code to compile, I should change all instances of

`#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 0, 0)` to

`#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 19, 3)`

**Except for** the one at line 1179 in `os_dep/linux/ioctl_cfg80211.c`

Still the same symptoms as #217, though, so I am back on 5.19.1

Do note that I didn't try 5.19.2

**Comment by CGarces** [comment]
Should be 
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 19, 2)

**Comment by MaxG87** [comment]
Fixed with 610b283b1e117afad686147d9b37992d5c4deb6e.
