### ISSUE TITLE
kernel lock

### ISSUE THREAD

**Issue by davidndian** [cilynx/rtl88x2bu#222]
![image](https://user-images.githubusercontent.com/111057228/192755295-5c45e343-f566-49bf-87c1-5664a86e5406.png)

channel 13 was allowed in my country , when i was pentesting on one of my routers which was on  channel 13 i was facing with the following message

**Comment by MaxG87** [comment]
Unfortunately I only fix compile errors. I am unable to extend the features or to fix complicated issues like the one reported. I am very sorry.
