### ISSUE TITLE
The Problem wirt RTL8812BU

### ISSUE THREAD

**Issue by noelj-osoftag** [cilynx/rtl88x2bu#228]
Hello. Here are the Problems with RTL8812BU devices: Error-95 operation not supported. I would appreciate any Help. @cilynx 

Here are the Commands i run for an dkms install. 

kali commands for rtl88x2bu: 
Kernel: 5.18.0 kali 2022.3 virtualbox
Device: TP-Link T3U AC1300 mini V1. (RTL8812BU). 

running root terminal!

1: sudo apt update
2: sudo apt upgrade
3: sudo apt install -y dkms git bc
4: git clone https://github.com/cilynx/rtl88x2BU
5: cd rtl88x2BU
6: make 		

warning:			make[1]: Entering directory '/usr/src/linux-headers-5.18.0-kali7-amd64'
				warning: the compiler differs from the one used to build the kernel
  				The kernel was built by: gcc-11 (Debian 11.3.0-5) 11.3.0
  				You are using:           gcc-11 (Debian 11.3.0-6) 11.3.0

at the end im getting:	
				
				Skipping BTF generation for /root/rtl88x2BU/88x2bu.ko due to unavailability of vmlinux
				make[1]: Leaving directory '/usr/src/linux-headers-5.18.0-kali7-amd64'

7: sudo make install	
		
is this the correct output?
				
				install -p -m 644 88x2bu.ko  /lib/modules/5.18.0-kali7-amd64/kernel/drivers/net/wireless/
				/sbin/depmod -a 5.18.0-kali7-amd64

8: sudo reboot now

After installing i hit iwconfig and the following output is displayed: 
unassociated Nickname:"<WIFI@REALTEK>"
Mode:Managed etc...
the T3U has 2.4 and 5.0 ghz and iwconfig shows only 2.4ghz. 
when i try to set Monitor mode with airmon, it doesnt do anything. with "sudo iw wlan0 set monitor control" im getting:
command failed: operation not supported (-95)

**Comment by MaxG87** [comment]
I am not sure anyone ever used `make install`. Could you try to load your module using `insmod` first? After that, there is either a Debian package or the `deploy.sh` script.
