### ISSUE TITLE
Ubuntu 22.04 5.15.0.50 unknown symbol in module

### ISSUE THREAD

**Issue by ollie-campbell** [cilynx/rtl88x2bu#229]
Hi,

Just in case anyone else has run into this issue, with Ubuntu 22.04 (kernel 5.15.0.50). When I tried to 'insmod 88x2bu.ko' I was getting:

ERROR: Could not insert module 88x2bu.ko: Unknown symbol in module

Using dmesg I could see that it was complaining about cfg80211, which 'modinfo cfg80211' showed as installed and OK.

I had to run 'sudo modprobe cfg80211' and then repeat the insmod command.

All working now.

**Comment by itsjillard** [comment]
Thanks for this. This worked on Linux Mint

**Comment by miguel-gh** [comment]
thank you!! It worked also for kerel 6.1.0-20 (Debian 12)
