### ISSUE TITLE
Ubuntu on RPi unable to compile/install

### ISSUE THREAD

**Issue by Shane-M2** [cilynx/rtl88x2bu#242]
While trying to install/configure the drivers on a fresh install of Ubuntu, I am receiving these errors;

Building module:
cleaning build area...
'make' -j 4 KVER=5.15.0-1024-raspi src=/usr/src/rtl88x2bu-5.8.7.1...(bad exit status: 2)
ERROR (dkms apport): binary package for rtl88x2bu: 5.8.7.1 not found
Error! Bad return status for module build on kernel: 5.15.0-1024-raspi (aarch64)
Consult /var/lib/dkms/rtl88x2bu/5.8.7.1/build/make.log for more information.

Is there a driver available for a RPi while running Ubuntu?  Same error is seen with the 5.19 kernel also.

**Comment by MaxG87** [comment]
Have you inspected the make.log? That should provide you with necessary information.
However, I am unable to build it on RPi too, because RPi does not provide kernel headers currently. I am using Raspbian, but maybe Ubuntu suffers the same issue.
