### ISSUE TITLE
issue with building driver

### ISSUE THREAD

**Issue by kajtekajtek** [cilynx/rtl88x2bu#248]
Trying to build this driver with make command on arch 6.3.4 results with this output

`/bin/sh: line 1: bc: command not found
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.3.4-arch1-1/build M=/home/kajtek/builds/rtl88x2bu  modules
/bin/sh: line 1: bc: command not found
  CC [M]  /home/kajtek/builds/rtl88x2bu/core/rtw_cmd.o
  CC [M]  /home/kajtek/builds/rtl88x2bu/core/rtw_security.o
  CC [M]  /home/kajtek/builds/rtl88x2bu/core/rtw_debug.o
/home/kajtek/builds/rtl88x2bu/core/rtw_debug.c: In function 'dump_drv_version':
/home/kajtek/builds/rtl88x2bu/core/rtw_debug.c:45:69: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
   45 |         RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
      |                                                                     ^
In file included from /home/kajtek/builds/rtl88x2bu/include/drv_types.h:60,
                 from /home/kajtek/builds/rtl88x2bu/core/rtw_debug.c:17:
/home/kajtek/builds/rtl88x2bu/core/rtw_debug.c:45:51: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
   45 |         RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
      |                                                   ^~~~~~~~
/home/kajtek/builds/rtl88x2bu/include/rtw_debug.h:254:46: note: in definition of macro 'RTW_PRINT_SEL'
  254 |                         _seqdump(sel, fmt, ##arg) /*rtw_warn_on(1)*/; \
      |                                              ^~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:252: /home/kajtek/builds/rtl88x2bu/core/rtw_debug.o] Error 1
make[1]: *** [Makefile:2025: /home/kajtek/builds/rtl88x2bu] Error 2
make: *** [Makefile:2392: modules] Error 2`

**Comment by MaxG87** [comment]
The first few characters already point to a possible issue: `bc` is not available, but it is required for the build process. Please try to install it before you proceed with compilation.
