### ISSUE TITLE
Suggesting deleting cfg80211.ko is really dangerous

### ISSUE THREAD

**Issue by char0n** [cilynx/rtl88x2bu#249]
After running “sudo rm -f /lib/modules/*/updates/net/wireless/cfg80211.ko” I cannot longer use any external wifi adapter. Is this really something we should be doing?

**Comment by MaxG87** [comment]
I am sorry, I wasn't aware of such a danger. I only have one WIFI adapter at all. I will rephrase that section.

**Comment by MaxG87** [comment]
I improved the section in the [latest commit](https://github.com/cilynx/rtl88x2bu/commit/49bec19134c1c3d55bf949737cd3d7905a06ac08) and linked to this issue. I leave it open for some time so others feel encouraged to report their experiences (other approaches, fixes, etc.) here.
