### ISSUE TITLE
lot of error while downloading

### ISSUE THREAD

**Issue by SujalMeghwal** [cilynx/rtl88x2bu#266]
┌──(root㉿kali)-[~/Downloads/rtl88x2bu]
└─# make                                 
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.6.9-amd64/build M=/root/Downloads/rtl88x2bu  modules
make[1]: Entering directory '/usr/src/linux-headers-6.6.9-amd64'
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_cmd.o
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_security.o
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_debug.o
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_io.o
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_ioctl_query.o
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_ioctl_set.o
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_ieee80211.o
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_mlme.o
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_mlme_ext.o
/root/Downloads/rtl88x2bu/core/rtw_mlme_ext.c: In function ‘rtw_txpwr_init_regd’:
/root/Downloads/rtl88x2bu/core/rtw_mlme_ext.c:194:21: warning: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
  194 |                 if (strcmp(exc->regd_name, regd_str(TXPWR_LMT_NONE)) == 0)
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/Downloads/rtl88x2bu/include/drv_types.h:62,
                 from /root/Downloads/rtl88x2bu/core/rtw_mlme_ext.c:17:
/root/Downloads/rtl88x2bu/include/rtw_rf.h:205:14: note: source object ‘regd_name’ of size 0
  205 |         char regd_name[0];
      |              ^~~~~~~~~
/root/Downloads/rtl88x2bu/core/rtw_mlme_ext.c:196:26: warning: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
  196 |                 else if (strcmp(exc->regd_name, regd_str(TXPWR_LMT_WW)) == 0)
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/Downloads/rtl88x2bu/include/rtw_rf.h:205:14: note: source object ‘regd_name’ of size 0
  205 |         char regd_name[0];
      |              ^~~~~~~~~
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_mi.o
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_wlan_util.o
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_vht.o
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_pwrctrl.o
  CC [M]  /root/Downloads/rtl88x2bu/core/rtw_rf.o
In file included from /root/Downloads/rtl88x2bu/include/drv_types.h:60,
                 from /root/Downloads/rtl88x2bu/core/rtw_rf.c:17:
/root/Downloads/rtl88x2bu/core/rtw_rf.c: In function ‘dump_txpwr_lmt’:
/root/Downloads/rtl88x2bu/core/rtw_rf.c:1168:67: warning: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
 1168 |                                                                 , strcmp(ent->regd_name, rfctl->regd_name) == 0 ? rf_path_char(path) : ' ');
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/Downloads/rtl88x2bu/include/rtw_debug.h:265:46: note: in definition of macro ‘_RTW_PRINT_SEL’
  265 |                         _seqdump(sel, fmt, ##arg) /*rtw_warn_on(1)*/; \
      |                                              ^~~
In file included from /root/Downloads/rtl88x2bu/core/rtw_rf.c:18:
/root/Downloads/rtl88x2bu/include/hal_data.h:341:14: note: source object ‘regd_name’ of size 0
  341 |         char regd_name[0];
      |              ^~~~~~~~~
/root/Downloads/rtl88x2bu/core/rtw_rf.c: In function ‘_rtw_txpwr_lmt_get_by_name’:
/root/Downloads/rtl88x2bu/core/rtw_rf.c:1380:21: warning: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
 1380 |                 if (strcmp(ent->regd_name, regd_name) == 0) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/Downloads/rtl88x2bu/include/hal_data.h:341:14: note: source object ‘regd_name’ of size 0
  341 |         char regd_name[0];
      |              ^~~~~~~~~
In function ‘_rtw_txpwr_lmt_get_by_name’,
    inlined from ‘rtw_txpwr_lmt_get_by_name’ at /root/Downloads/rtl88x2bu/core/rtw_rf.c:1397:8:
/root/Downloads/rtl88x2bu/core/rtw_rf.c:1380:21: warning: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
 1380 |                 if (strcmp(ent->regd_name, regd_name) == 0) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/Downloads/rtl88x2bu/include/hal_data.h: In function ‘rtw_txpwr_lmt_get_by_name’:
/root/Downloads/rtl88x2bu/include/hal_data.h:341:14: note: source object ‘regd_name’ of size 0
  341 |         char regd_name[0];

**Comment by MaxG87** [comment]
I was struck by these issues too after upgrading to Debian Testing recently. You can get around these by either using an older version of GCC or disabling the errors in the Makefile. A fix for that (very likely disabling it) will be merged soon.

**Comment by SujalMeghwal** [comment]
how I can disable "makefile"
