### ISSUE TITLE
Need help on DFS Testing in RPI platform. 

### ISSUE THREAD

**Issue by kpandu987** [cilynx/rtl88x2bu#269]
Hi Cilynx,

I used below driver source code to bring up AP for 5G  with DFS in RPI platform,
https://github.com/cilynx/rtl88x2bu/tree/5.8.7.1_35809.20191129_COEX20191120-7777

Now, I am able to connect wireless clients with DFS freq range . 

Kindly suggest how to simulate RADAR pulse for DFS testing .

**Comment by cilynx** [comment]
This is quite far outside my wheelhouse -- I don't honestly know if this is possible with Wifi hardware as opposed to a real SDR.

A couple related resources I found on a quick search:
https://wifimetrix.com/dfs-testing/
https://github.com/adriangranados/dfs-pulse-tester
