### ISSUE TITLE
boot time reduction?

### ISSUE THREAD

**Issue by HansElectrumpet** [cilynx/rtl88x2bu#41]
Hi,

I don't know if this is really an issue or an inevitable. When starting up there are about 14 seconds between the moment the module gets recognised by the system as an USB device and the moment that the initialisation process starts. I am trying to reduce boot time. Is there a way to speed up the process now or is it possible in a future version?

(4.19.94-bone44), Buster on a PocketBeagle (highest current version).

dmesg output:
[   19.595409] usb 1-1: Manufacturer: Realtek

[   19.595416] usb 1-1: SerialNumber: 123456

[   33.475816] cfg80211: Loading compiled-in X.509 certificates for regulatory database

[   33.490036] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'

[   34.111534] RTW: module init start

Thanks, Hans.

**Comment by MaxG87** [comment]
I am experiencing similar issues, not as long, but noticeable. It sucks but I do not know a workaround.
