### ISSUE TITLE
How do I set this up for Fedora?

### ISSUE THREAD

**Issue by donuts12** [cilynx/rtl88x2bu#56]
I tried a few and just kept giving me errors , on ubuntu it worked fine however on fedora its not, any help or provide instructions for fedora users?

**Comment by Medullitus** [comment]
CAN ANYONE KNOW THE DEVELOPER WHERE IS IT ????????????

**Comment by Iniesta8** [comment]
The driver works for me on Fedora 32...

Steps:

1. Install the package dkms:
`sudo dnf install dkms`

2. Follow the dkms installation instructions in README.md:
https://github.com/cilynx/rtl88x2bu#dkms-installation

**Comment by bernhara** [comment]
Works for me too.
