### ISSUE TITLE
build failed in 5.7.0-kali1-amd64

### ISSUE THREAD

**Issue by MiChaelinzo** [cilynx/rtl88x2bu#75]
<img width="477" alt="help" src="https://user-images.githubusercontent.com/68110223/91672071-a064aa80-eb34-11ea-92cf-c5a126267142.PNG">
<img width="614" alt="help2" src="https://user-images.githubusercontent.com/68110223/91672073-a35f9b00-eb34-11ea-9e0c-8dce30752111.PNG">

**Comment by gabe-swp** [comment]
I'm also getting this exact error. Do you know an earlier version of Kali I could use whilst I wait for this to be fixed?

**Comment by marmocc** [comment]
This problem also happens on kernel 5.5, it is not a driver problem.
The fix is installing a package called "bc" or at least, that's what worked for me.

**Comment by MiChaelinzo** [comment]
> This problem also happens on kernel 5.5, it is not a driver problem.
> The fix is installing a package called "bc" or at least, that's what worked for me.

sudo apt-get install bc?
https://www.gnu.org/software/bc/

**Comment by marmocc** [comment]
> > This problem also happens on kernel 5.5, it is not a driver problem.
> > The fix is installing a package called "bc" or at least, that's what worked for me.
> 
> sudo apt-get install bc?
> https://www.gnu.org/software/bc/

Yep, that's it.

**Comment by MiChaelinzo** [comment]
I still can't compile driver source with 
$ make clean
$ make
I have Installed the Kernel Header File
automatically with $ sudo apt-get install linux-headers-$(uname -r)
I don't know if the instruction for Linux in TP-Link website is outdated or it doesn't have instruction for Debian
